### ISSUE TITLE
Monitoring - KDE Neon Not Supported

### ISSUE THREAD

**Issue by DerekRoberts** [mistio/deploy_collectd#12]
Please allow monitoring of KDE Neon.  It's built on Ubuntu 16.04 LTS and more or less a replacement for Kubuntu.  The use case is Ubuntu LTS for people who prefer KDE.

> wget -O mist_collectd.py https://github.com/mistio/deploy_collectd/raw/master/local_run.py && $(command -v sudo) python mist_collectd.py ... -m monitor1.mist.io

TASK: [Check support for OS family] ******************************************* 
failed: [localhost] => {"failed": true}
msg: Distro Neon not supported,

**Comment by mgogoulos** [comment]
We'll test this now and update the issue
